# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fKwvSwyI8yi9BPg0-2OFtUVbG12e69dc
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_squared_error
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

import xgboost as xgb
import warnings
warnings.filterwarnings('ignore')

import pickle

df=pd.read_csv('/content/2015.csv')

print(df.head())

df.info()

print("Dataset Shape:",df.shape)

print(df.isnull().sum())

df.fillna(df.mean(numeric_only=True),inplace=True)

df.rename(columns={
    "Economy (GDP per Capita)":"Economy",
    "Health (Life Expectancy)":"Health",
    "Trust (Government Corruption)":"Trust"
},inplace=True)

le=LabelEncoder()

df["Region"]=le.fit_transform(df["Region"])
df["Country"]=le.fit_transform(df["Country"])

print(df.head())

numerical_cols=df.select_dtypes(include=np.number).columns

for i in numerical_cols:
    df[[i]].boxplot()
    plt.title(f'Boxplot of {i}')
    plt.show()

print(df.describe())

sns.histplot(df["Happiness Score"],kde=True)
plt.title("Distribution of Happiness Score")
plt.show()

sns.scatterplot(x=df["Economy"],y=df["Happiness Score"])
plt.title("Economy vs Happiness Score")
plt.show()

sns.scatterplot(x=df["Health"],y=df["Happiness Score"])
plt.title("Health vs Happiness Score")
plt.show()

plt.figure(figsize=(10,6))
sns.heatmap(df.corr(),annot=True,cmap="coolwarm")
plt.title("Correlation Matrix")
plt.show()

features = [
"Economy",
"Family",
"Health",
"Freedom",
"Trust",
"Generosity"
]

x = df[features]

y = df["Happiness Score"]

x_train,x_test,y_train,y_test=train_test_split(
    x,y,random_state=42,test_size=0.2
)

dtr=DecisionTreeRegressor(random_state=42)

dtr.fit(x_train,y_train)

y_train_pred=dtr.predict(x_train)
y_test_pred=dtr.predict(x_test)

print("Decision Tree")

print("Train R2:",r2_score(y_train,y_train_pred)*100)
print("Test R2:",r2_score(y_test,y_test_pred)*100)

rfr=RandomForestRegressor(n_estimators=100,random_state=42)

rfr.fit(x_train,y_train)

y_train_pred=rfr.predict(x_train)
y_test_pred=rfr.predict(x_test)

print("\nRandom Forest")

print("Train R2:",r2_score(y_train,y_train_pred)*100)
print("Test R2:",r2_score(y_test,y_test_pred)*100)

xg_reg = xgb.XGBRegressor()
xg_reg.fit(x_train,y_train)

y_train_pred=xg_reg.predict(x_train)
y_test_pred=xg_reg.predict(x_test)

print("\nXGBoost")

print("Train R2:",r2_score(y_train,y_train_pred)*100)
print("Test R2:",r2_score(y_test,y_test_pred)*100)

reg=LinearRegression()

reg.fit(x_train,y_train)

y_train_pred=reg.predict(x_train)
y_test_pred=reg.predict(x_test)

print("\nLinear Regression")

print("Train R2:",r2_score(y_train,y_train_pred)*100)
print("Test R2:",r2_score(y_test,y_test_pred)*100)

sample_parameters = x.iloc[0].values.tolist()

print("Sample parameters:",sample_parameters)

prediction = rfr.predict([sample_parameters])

print(f"Prediction for sample parameters: {prediction[0]:.3f}")

with open("bestmodel.pkl","wb") as f:
    pickle.dump(reg,f)